#!/bin/env bash
#该脚本用于将跳板机上的yunwei用户的公钥推送到局域网内可以ping通的服务器上，并实现免密登录

#首先查看自身是否有公钥文件
home_dir=/home/yunwei
[ ! -f $home_dir/.ssh/id_rsa.pub ] && ssh-keygen -P '' -f $home_dir/.ssh/id_rsa &>/dev/null

#循环检查局域网内的服务器网络连通性并推送公钥
ip_txt=$home_dir/ip.txt

for i in `cat $ip_txt`
do

        ip=`echo $i|cut -d: -f1`
        pass=`echo $i|cut -d: -f2`

        ping -c2 $ip &>/dev/null

        if [ $? -eq 0 ];then
           echo $ip >> $home_dir/ip_up.txt

                /usr/bin/expect <<-END &>/dev/null
                spawn ssh-copy-id root@$ip
                expect {
                        "(yes/no)" {send "yes\r";exp_continue}
                        "password:" {send "$pass\r"}
                       }
                expect eof
                END
          else
                echo $ip >> $home_dir/ip_down.txt
        fi

done

#测试
test_ip=`head -1 ~/ip_up.txt`
ssh root@$test_ip hostname &>/dev/null
[ $? -eq 0 ] && echo "公钥推送成功"
